name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master if you use that branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Change if you need a different version

    - name: Install dependencies
      run: |
        npm install

    - name: Build the project
      run: |
        npm run build  # Adjust if you use another build command

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out  # Update with the directory where the build output is located, e.g., 'build' or 'dist'
