name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use Node.js version 14 (or adjust based on your needs)

    - name: Install dependencies
      run: npm install  # Install dependencies from package.json

    - name: Build project
      run: npm run build  # Build the Next.js app

    - name: Export static site
      run: npm run export  # Export static files for GitHub Pages

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out  # The directory that contains the static files (default is ./out)
